// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BullDoghs.Models
{
    [Table("LoginInfo")]
    public partial class LoginInfo
    {
        [Key]
        public int UserPK { get; set; }
        [Required]
        [StringLength(50)]
        [RegularExpression(@"^[a-zA-Z0-9\.]+@bdhigh\.edu$", ErrorMessage = "Email Address as ****@bdhigh.edu is required")]
        [Display(Name = "User Name", Prompt = "Example Email Address:  ***.***@bdhigh.edu")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100)]
        
        public string UserPass { get; set; }
        [Required]
        [StringLength(50)]
        public string FullName { get; set; }
        //[Required]
        [StringLength(50)]
        public string UserRole { get; set; }
    }
}