// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BullDoghs.Models
{
    [Table("tbCourse")]
    public partial class tbCourse
    {
        public tbCourse()
        {
            tbCourseSections = new HashSet<tbCourseSection>();
        }

        [Key]
        [StringLength(50)]
        public string CourseTitle_PK { get; set; }
        [Required]
        [StringLength(300)]
        public string Course_Description { get; set; }

        [InverseProperty("CourseTitle_FKNavigation")]
        public virtual ICollection<tbCourseSection> tbCourseSections { get; set; }
    }
}