// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BullDoghs.Models
{
    [Table("tbRegistration")]
    public partial class tbRegistration
    {
        [Key]
        [StringLength(10)]
        public string CourseRegistrationID_PK { get; set; }
        public double CourseScore { get; set; }
        [Required]
        [StringLength(30)]
        public string CourseStatus { get; set; }
        public int CourseSectionID_FK { get; set; }
        [Required]
        [StringLength(20)]
        public string StudentID_FK { get; set; }

        [ForeignKey("CourseSectionID_FK")]
        [InverseProperty("tbRegistrations")]
        public virtual tbCourseSection CourseSectionID_FKNavigation { get; set; }
        [ForeignKey("StudentID_FK")]
        [InverseProperty("tbRegistrations")]
        public virtual tbStudent StudentID_FKNavigation { get; set; }
    }
}