// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BullDoghs.Models
{
    [Table("tbStudent")]
    public partial class tbStudent
    {
        public tbStudent()
        {
            tbRegistrations = new HashSet<tbRegistration>();
        }

        [Key]
        [StringLength(20)]
        public string StudentID_PK { get; set; }
        [Required]
        [StringLength(50)]
        public string StudentName { get; set; }
        public int Grade { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }

        [InverseProperty("StudentID_FKNavigation")]
        public virtual ICollection<tbRegistration> tbRegistrations { get; set; }
    }
}