// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BullDoghs.Models
{
    [Table("tbTeacher")]
    public partial class tbTeacher
    {
        public tbTeacher()
        {
            tbCourseSections = new HashSet<tbCourseSection>();
        }

        [Key]
        [StringLength(20)]
        public string TeacherID_PK { get; set; }
        [Required]
        [StringLength(50)]
        public string TeacherName { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [StringLength(20)]
        public string PhoneNumber { get; set; }

        [InverseProperty("TeacherID_FKNavigation")]
        public virtual ICollection<tbCourseSection> tbCourseSections { get; set; }
    }
}