// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BullDoghs.Models
{
    public partial class Team105DBContext : DbContext
    {
        public Team105DBContext()
        {
        }

        public Team105DBContext(DbContextOptions<Team105DBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<LoginInfo> LoginInfos { get; set; }
        public virtual DbSet<tbCourse> tbCourses { get; set; }
        public virtual DbSet<tbCourseSection> tbCourseSections { get; set; }
        public virtual DbSet<tbRegistration> tbRegistrations { get; set; }
        public virtual DbSet<tbStudent> tbStudents { get; set; }
        public virtual DbSet<tbTeacher> tbTeachers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<tbCourseSection>(entity =>
            {
                entity.HasOne(d => d.CourseTitle_FKNavigation)
                    .WithMany(p => p.tbCourseSections)
                    .HasForeignKey(d => d.CourseTitle_FK)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbCourseSection_tbCourse");

                entity.HasOne(d => d.TeacherID_FKNavigation)
                    .WithMany(p => p.tbCourseSections)
                    .HasForeignKey(d => d.TeacherID_FK)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbCourseSection_tbTeacher");
            });

            modelBuilder.Entity<tbRegistration>(entity =>
            {
                entity.Property(e => e.CourseRegistrationID_PK).IsFixedLength();

                entity.HasOne(d => d.CourseSectionID_FKNavigation)
                    .WithMany(p => p.tbRegistrations)
                    .HasForeignKey(d => d.CourseSectionID_FK)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbRegistration_tbCourseSection");

                entity.HasOne(d => d.StudentID_FKNavigation)
                    .WithMany(p => p.tbRegistrations)
                    .HasForeignKey(d => d.StudentID_FK)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbRegistration_tbStudent");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}